name: Build and publish to PyPI

# just for tests
on:
  push:
    branches: ["**"]

# on: 
#   push:
#     tags:
#        - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: |
          docker build \
            -t apyefa:release -f .devcontainer/Dockerfile .

      - name: Build package
        run: |
          docker run --rm \
            -v $PWD/app \
            apyefa:release \
            uv run python -m build

      - name: Get tags
        run: |
          docker run --rm \
            -v $PWD/app \
            apyefa:release \
            git describe --tags
      
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-release
          path: dist/